config/routes.rb
Crunchmate::Application.routes.draw do

  root :to => "recipes#index"

  resources :users 
  resources :sessions, only: [:new, :create, :destroy]

  match '/home' => "recipes#index"

  match 'auth/:provider/callback' => 'sessions#create'

  get '/recipes/search', to: 'recipes#search'
  get '/recipes/:id/' => 'recipes#show'

  match '/signup' => 'users#new'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base



#omniAuth method for sessionscreate controller
  def self.create_with_omniauth(auth)
    create! do |user|
      user.username = auth["info"]["nickname"]
      user.password_digest = SecureRandom.urlsafe_base64
      user.password = auth["info"]["secret"] 
      user.password_confirmation = auth["info"]["secret"] 
      user.provider = auth["provider"]
      user.email = auth["uid"]
      user.uid = auth["uid"]
    end
  end

  attr_accessible :username, :email, :password, :password_digest, :password_confirmation, :provider, :uid
  has_secure_password


  # before_save { |user| user.email = user.email.downcase }
  before_save :create_remember_token

  #After matching one or more alphanumeric characters, if there's a separator it must be followed by one or more alphanumerics; repeat as needed.
  VALID_USERNAME_REGEX = /^[A-Za-z0-9]+(?:[ _-][A-Za-z0-9]+)*$/
  validates :username,  presence: true, format: {with: VALID_USERNAME_REGEX }, length: { maximum: 15 }, uniqueness: true

  # Must have at least one word character -> an @ sign -> at least one letter,digit, hyphen, or dot -> 
  #a literal dot -> at least one letter (no repeating dots)
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, uniqueness: { case_sensitive: false }


  validate :email_or_provider
  validate :email_format
  validate :password_length

  def email_or_provider
    unless (self.email && self.password && self.password_confirmation) || self.provider
      flash[:error] = "Please Sign in."
    end
  end

  def email_format
    if(email)
      unless(email =~ VALID_EMAIL_REGEX)
        return "error message"
      end
    end
  end

  def password_length
    if(password.nil? or password.length < 7 )
        return "Password must be at least 6 characters."
    end
  end

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  require 'open-uri'

  def index
    @params = params
  end

  def search
    @hours = params[:hours]
    @minutes = params[:minutes]
    @seconds = ((@hours.to_i * 60) + @minutes.to_i) * 60
    @course = params[:courses]
    @search = params[:search].split.join("+")
    @score = params[:rating]

    if @course == "Lunch" || "Snacks"
      @course = "Lunch and Snacks"
    end

    if @course == "Breakfasts"
      @course = "Breakfast and Soups"
    end


    yumid = YUMMLY_APP_ID
    yumkey = YUMMLY_APP_KEY

    #calls the Yummly API with search params to return an index of recipes
    if @course.blank?
      @url = URI::encode("https://api.yummly.com/v1/api/recipes?_app_id="+yumid+"&_app_key="+yumkey+"&q=#{@search}&maxTotalTimeInSeconds=#{@seconds}")
    else
      @url = URI::encode("https://api.yummly.com/v1/api/recipes?_app_id="+yumid+"&_app_key="+yumkey+"&q=#{@search}&allowedCourse[]=course^course-#{@course}&maxTotalTimeInSeconds=#{@seconds}")
    end

    @response = JSON.load(open(@url))["matches"].map {|listing| 
      {"image" => listing["smallImageUrls"].first,
      "time" => listing["totalTimeInSeconds"].to_i / 60,
      "name" => listing["recipeName"],
      "recipeId" => listing["id"],
      "items" => listing["ingredients"]}
    }

  end

  def show

    yumid = YUMMLY_APP_ID
    yumkey = YUMMLY_APP_KEY
    
    #calls the Yummly API to return the JSON for a specific recipe, and extracts the sourceRecipeUrl
    @url_y = "https://api.yummly.com/v1/api/recipe/#{params[:id]}?_app_id="+yumid+"&_app_key="+yumkey
    @title = JSON.load(open(@url_y))['name']
    @img = JSON.load(open(@url_y))["images"].map { |pic|
      {"bigPic" => pic["hostedLargeUrl"]}
    }
    @site = JSON.load(open(@url_y))['source']['sourceRecipeUrl']
    @location = JSON.load(open(@url_y))['source']['sourceDisplayName']
    @ingredients = JSON.load(open(@url_y))["ingredientLines"]
    @snippet = JSON.load(open(@url_y))['attribution']['html']
    @prep = JSON.load(open(@url_y))['totalTime']

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :user_finder, :only => [:create]

  def new
    
  end

  def create
    @user = user_finder
    if @user
      sign_in(@user)
      redirect_to root_path
    else
      flash[:error] = "Error"
      render :new
    end
  end

  def destroy
    sign_out
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to root_path
    else
      flash[:error] = "Error"
      render :new
    end
  end

  # def edit
  #   @user = User.find(params[:id])
  # end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper


  def blank_message
    case rand(1..6)
      when 1
        "Sorry, I couldn't find anything.Maybe you need more time...?"
      when 2
        "No results found. Did you try specifying a course?"    
      when 3
        "Far out! Maybe you shouldn't specify a course...?"
      when 4
        "That sounds good, but I didn't find anything."
      when 5
        "Do you really even have time to be cooking right now?"
      when 6
        "???"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    user = current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
     @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
    redirect_to signin_path
  end

  def user_finder 
    if(params[:session])
      @user = User.find_by_email(params[:session][:email])
    else
      auth = request.env["omniauth.auth"]
      @user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    end
  end



end

app/views/layouts/application.html.haml
!!! 5
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class=\"ie6\" lang=\"en\">
/[if IE 7 ]    <html class=\"ie7\" lang=\"en\">
/[if IE 8 ]    <html class=\"ie8\" lang=\"en\">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  %meta{ :charset => "utf-8" }

  -# Uncomment to make IE8 render like IE7
  -# meta http-equiv="X-UA-Compatible" content="IE=7"

  -# Set the viewport width to device width for mobile
  %meta{ :name => "author", :content => "Joshua Shelto" }
  %meta{ :name => "description", :content => "CrunchMate helps you find the recipes that fit your schedule" }
  %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

  %title= content_for?(:title) ? yield(:title) : "CrunchMate"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

%body
  
  = yield

  = javascript_include_tag "application"

app/views/recipes/_recipe-navbar.html.erb
<%= form_tag({controller: "recipes", action: "search"}, method: :get) do %> 

  <div>
    <div class= "row">
      <div class="large-8 columns">
        <label for="right-label" class="right"><strong>I have</strong></label>
        <select id="customDropdown1" name="hours" class="medium"> 
            <option> <%= 0 %> </option> 
            <option> <%= 1 %> </option> 
          <% (2..10).each do |i| %> 
            <option> <%= i %>  </option>
          <% end %>
        </select> <strong>hour(s)</strong>
        <select id="customDropdown1" name="minutes" class="f-dropdown"> 
        <option> <%= 1 %> </option>
          <% (2..60).each do |i| %> 
            <option><%= i %>  </option>
          <% end %>
        </select> <strong>minute(s)</strong>
      </div>
    </div>

    <div class="row">
      <div class="small-8">
        <div class="row">
          <div class="small-4 columns">
            <label for="right-label" class="right"><strong>to make something </strong> </label>
            <input type="text" id="right-label" name="search" placeholder="baked ziti..."><strong>-related</strong>
          </div>
        </div>
      </div>
    </div>

    <div class= "row">
      <div class="large-8 columns">
        <label for="right-label" class="right"><strong>for</strong></label>
        <select id="customDropdown2" name="courses" class="f-dropdown"> 
            <option> </option>
            <option> <%= "Appetizers" %> </option>
            <option> <%= "Breakfast and Soups" %> </option>
            <option> <%= "Beverages" %> </option>
            <option> <%= "Cocktails" %> </option>   
            <option> <%= "Desserts" %> </option>
            <option> <%= "Lunch and Snacks" %> </option>
            <option> <%= "Main Dishes" %> </option> 
            <option> <%= "Salads" %> </option> 
            <option> <%= "Side Dishes" %> </option>   
        </select>
    </div>

  <%= submit_tag "Go!" %>

<% end %>


<!--     <div class= "row">
      <div class="large-4 columns">
        <label for="right-label" class="right"><strong>Course</strong></label>
        <select id="customDropdown1" name="course" class="medium">
          <option>Breakfast</option>
          <option>Lunch</option>
          <option>Main Dishes</option>
          <option>Snacks</option>
          <option>Beverages</option>
        </select>
      </div>
    </div> -->

app/views/recipes/_recipe_query.html.erb
<div class="row">
  <%= form_tag({controller: "recipes", action: "search"}, method: :get) do %> 
    <div class="row large 12-columns">

      <div class="large-2 columns">
        <div class="row">
          <div class="large-5 columns">
            <label for="right-label" class="left inline" id="query-start"><strong>I have</strong></label>
          </div>
          <div class="large-7 pull-2 columns">
            <select id="customDropdown1" name="hours" class="tiny button dropdown secondary"> 
              <option> <%= 0 %> </option> 
              <option> <%= 1 %> </option> 
              <% (2..10).each do |i| %> 
              <option> <%= i %>  </option>
              <% end %>
            </select>
          </div>
        </div>
      </div>

      <div class="large-2 columns">
        <div class="row">
          <div class="large-5  pull-2 columns">
            <label for="right-label" class="left inline"><strong>hour(s)</strong></label>
          </div>
          <div class="large-7 pull-3 columns">
            <select id="customDropdown2" name="minutes" class="tiny button dropdown secondary"> 
              <option> <%= 1 %> </option>
              <% (2..60).each do |i| %> 
              <option> <%= i %>  </option>
              <% end %>
            </select>
          </div>
        </div>
      </div>

      <div class="large-4 columns">
        <div class="row">
          <div class="large-2 pull-2 columns">
            <label for="right-label" class="left inline"> <strong>minute(s)</strong></label>
          </div>
          <div class="large-5 pull-2 columns">
            <label for="right-label" class="left inline make-something"><strong>to make something </strong> </label>
          </div>
          <div class="large-5 pull-2 columns" id="searchbar">
            <input type="search" name="search" placeholder="baked ziti..." results="0">
          </div>
        </div>
      </div>

      <div class="large-4 columns">
        <div class="row">
          <div class="large-3 pull-2 columns">
            <label for="right-label" class="left inline"><strong>-related,</strong></label>
          </div>
          <div class="large-2 pull-2 columns">
            <label for="right-label" class="left inline"><strong> for</strong></label>
          </div>
          <div class="large-5 pull-3 columns">
            <select id="customDropdown3" name="courses" class="tiny button dropdown"> 
            <option> <%= "" %> </option>
            <option> <%= "Appetizers" %> </option>
            <option> <%= "Breakfasts" %> </option>
            <option> <%= "Beverages" %> </option>
            <option> <%= "Cocktails" %> </option>   
            <option> <%= "Desserts" %> </option>
            <option> <%= "Lunch" %> </option>
            <option> <%= "Main Dishes" %> </option> 
            <option> <%= "Salads" %> </option> 
            <option> <%= "Side Dishes" %> </option> 
            <option> <%= "Snacks" %> </option>  
            </select>
          </div>
          <div class="large-2 pull-2 columns">
            <%= submit_tag "Go!", class: "small button radius" %>
          </div>
        </div>
      </div>

    </div>  

  <% end %>
</div>

app/views/recipes/index.html.erb
<%= render "users/navigation" %>
<br>
<%= render "recipe_query" %>

<div class="intro alt-mobile">
  <h1>Welcome to CrunchMate</h1>
  <p>Use the search bar above to discover recipes to fit your schedule</p>
</div>

app/views/recipes/search.html.erb
<%= render "users/navigation" %>
<%= render "recipe_query" %>

<div class="row">
  <div class="large-5 push-4 columns">
    <center><h1> Recipes </h1></center>
    <% if @response.empty? %>
    <div class="small-12 columns">
      <center><h1><%= blank_message -%> </h1></center>
    </div>
    <% else %>
      <% @response.each do |x| %>
        <%= link_to(:controller => "recipes", :action => "show", :id => x["recipeId"]) do %>
          <div style="background-color: #F78D3F">
            <div style="padding-left:20px;">
              <h3> <%= x["name"] %> </h3> <br>
              <img src="<%= x["image"] %>" height="100" width="100"> 
              <div style="color: #102E37">
                Estimated prep time: <%= x["time"] %> minutes
              </div>
            </div>
          </div> 
        <% end %>
      <% end %>
    <% end %>  
  </div>  
</div>

app/views/recipes/show.html.erb
<% content_for :title, "CrunchMate | #{@title}" %>
<%= render "users/navigation" %>
<%= render "recipe_query" %></br>

<div class="row">
  <div class="recipe large-6 columns">
    <center>
      <h1><%= @title %></h1></br>
      <strong>Prep Time:</strong> <%= @prep %> </br>
      <a href="<%=@site %>"> Check out this recipe on <%= @location %> </a> </br>
      <a href="<%=@site %>"> <% @img.each do |i| %>
        <img src="<%= i["bigPic"] %>">
      <% end %></a> </br>
      </center>
      <a href="https://twitter.com/share" class="twitter-share-button" data-text="Thanks to Crunch-Mate, I was able to find a recipe for <%= @title %>!" data-count="none" data-hashtags="delicious" data-dnt="true">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      <a href="#"
        onclick="
          window.open(
            'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
            'facebook-share-dialog', 
            'width=626,height=436'); 
          return false;">
        Share on Facebook
      </a>

  </div>
  <div class="ingredients large-6 columns">
    <center>
      <h3 style="color: #F78D3F; background-color: #fff">Ingredients</h3>
      <ul class="no-bullet" style="color: #F78D3F">
        <% @ingredients.each do |l| %>
          <li>
            <%= l %>
          </li>
         <% end %>
        <small class="powered_by"><%=  raw @snippet %></small>
      </ul>
    </center>
  </div>
</div>

app/views/users/_navigation.html.erb
<nav class="top-bar">
  <ul>
    <li class="name">
      <h1><%= link_to "CrunchMate", "/home" %></h1>
    </li>
  </ul>
<!--   <section class="top-bar-section">
    <ul class="right" style="padding: 0 0 20 0;">
      <% if current_user %>
        <li class="divider"></li>
        <li class="has-form">Signed in as <strong><%= link_to current_user.username.capitalize, "/home" %></strong></li>
        <li class="has-form"><%= link_to "Sign out", signout_path %></li>
      <% else %>
        <li><%= link_to image_tag("social_tw.png", alt: "Sign in with Twitter", :width => 154, :height => 22), "/auth/twitter" %></li>
        <li><%= link_to image_tag("social_fb.png", alt: "Sign in with Facebook", :width => 154, :height => 22), "/auth/facebook" %></li>
      <% end %>
    </ul>
  </section> -->
</nav>

app/views/users/edit.html.erb
<form>
  <fieldset>
    <legend>Edit User</legend>
      <%= form_for(@user) do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username, :autofocus => true%>
      <% end %>
  </fieldset>
</form

app/views/users/new.html.erb
<form>
  <fieldset>
    <legend> Sign Up </legend>
                <div class="row">
                    <div class="large-6 columns">  
                        <%= link_to image_tag("social_tw.png", alt: "Sign in with Twitter"), "/auth/twitter" %>
                        <%= link_to image_tag("social_fb.png", alt: "Sign in with Facebook"), "/auth/facebook" %>
                    </div>
                </div>
              <%= form_for(@user) do |f| %>
                <div class="row">
                    <div class="large-6 columns">
                        <label>Username</label>
                        <%= f.text_field :username, :value=>"",:placeholder => "Username", :autofocus => true%>
                    </div>
                </div>
                <div class="row">
                    <div class="large-6 columns">
                        <label>Email</label>
                        <%= f.email_field :email, :value=>"",:placeholder => "your@email.com"%>
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="large-6 columns">
                        <label>Password</label>
                        <%= f.password_field :password, :value=>"",:placeholder => "Password" %>
                        <br />
                    </div>
                </div>
                <div class="row">
                    <div class="large-6 columns">
                        <label>Confirm Password</label>
                        <%= f.password_field :password_confirmation, :value=>"",:placeholder => "Password Confirmation" %>
                    </div>
                </div>

                <div class="row">
                    <div class="large-6 columns">
                        <%= f.button "Sign up" %>
                    </div>
                </div>

              <% end %>

              <%= link_to "Back to Crunch-Mate", root_url %>
    </fieldset>
</form>


  